Milestone 3
mrnadaara/React-Bookstore pull request #4
Opened 2020-06-26 15:53 UTC by mrnadaara

Purpose of this PR was to connect the CREATE_BOOK and REMOVE_BOOK actions with the React component and make our page dynamic.

The CREATE_BOOK action was connected with the BooksForm component and REMOVE_BOOK action was connected to the BooksList component

2020-06-27 08:26 UTC, shshamim63 requested changes
## :eagle: Changes Required :eagle: 
___
Hi @mrnadaara and @rmauritsson :wave: 
Great initiative. You have covered the most of the challenging tasks. But to declare this milestone as approved you need to cover some simple edge cases. Let's get to them.
___
### :spades: Mandatory Changes :spades: 
___
- The check of propType for the book component is not correct. Check the comment below.
- Your handleSubmit should mainly cover two major actions. 1. saves the new book in the Redux store(Which it is doing), 2. Should reset the component state(This section is missing). ![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/HandleSubmit.png)
___
### :clubs: Optional Changes :clubs: 
___
- The filter() method creates a new array and your book is an array. So I don't think you need to wrap the generated state in an array.
https://github.com/mrnadaara/React-Bookstore/blob/7ad145036a78df0e81d7e3e19be6cb21be4d3951/src/reducers/books.js#L8
The following format is the more appropriate one I believe. 
```js
      return state.filter(book => book.id !== action.payload.id);
```
- The method you have added to generate id can return duplicate ids.
https://github.com/mrnadaara/React-Bookstore/blob/7ad145036a78df0e81d7e3e19be6cb21be4d3951/src/actions/index.js#L3-L7
While I tried to create books It renders the following warning 
![image](https://user-images.githubusercontent.com/38625956/85918047-2d635d00-b881-11ea-90bc-9ea136504b3a.png)
It is related to the key property of your iterative component. There is a package called [uuid](https://www.npmjs.com/package/uuid) I will suggest you to use that one to get it done.
- As we have reducers predefined, so in propType while checking for the function, instead of declaring the default function I will suggest, you should check for isRequired. for example for Book component, it will look the following. 
```js
Book.propTypes = {
  // type-check for book object.
  onClick: PropTypes.func.isRequired,
};
```
Then you don't need to generate a default function for that.
___
#### Please resolve the mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-06-27 08:26 UTC, shshamim63 commented on src/components/Book/Book.jsx
>    book: PropTypes.objectOf(PropTypes.string),
PropTypes.objectOf is used when describing an object whose properties are all the same type. But your book does not contain the same type of properties. So check the types properly.

2020-06-27 08:26 UTC, shshamim63 commented on src/components/Book/Book.jsx
> +    <td><button type="button" onClick={onClick}>Delete</button></td>
I think the naming of the prop function OnClick is confusing with the default event handler method. And most of the 
renowned developers insist to avoid this kind of naming.

2020-06-28 16:30 UTC, fatymahmed approved these changes
## Hi @mrnadaara @rmauritsson,
### Great job in this milestone 🎉🎉
### It's a 👍🏾 from me!
## ✔️ Approved!

2020-06-29 12:30 UTC, merged